export const data = [
	{
		_id: 1,
		name: 'Olivia Rhye',
		status: 'Active',
		course: 'Product Designer',
		emailAddress: 'olivia@untitledui.com',
		duration: '3 months',
	},
	{
		_id: 2,
		name: 'Sanyaolu Rhye',
		status: 'Graduate',
		course: 'Product Designer',
		emailAddress: 'olivia@untitledui.com',
		duration: '3 months',
	},
	{
		_id: 3,
		name: 'Fakile Rhye',
		status: 'Active',
		course: 'Product Designer',
		emailAddress: 'fakile@gmail.com',
		duration: '3 months',
	},
	{
		_id: 4,
		name: 'Fatokun Rhye',
		status: 'Graduate',
		course: 'UI/UX Designer',
		emailAddress: 'hello@untitledui.com',
		duration: '3 months',
	},
	{
		_id: 1,
		name: 'Olivia Rhye',
		status: 'Active',
		course: 'Product Designer',
		emailAddress: 'olivia@untitledui.com',
		duration: '3 months',
	},
	{
		_id: 2,
		name: 'Sanyaolu Rhye',
		status: 'Graduate',
		course: 'Product Designer',
		emailAddress: 'olivia@untitledui.com',
		duration: '3 months',
	},
	{
		_id: 3,
		name: 'Fakile Rhye',
		status: 'Active',
		course: 'Product Designer',
		emailAddress: 'fakile@gmail.com',
		duration: '3 months',
	},
	{
		_id: 4,
		name: 'Fatokun Rhye',
		status: 'Active',
		course: 'UI/UX Designer',
		emailAddress: 'hello@untitledui.com',
		duration: '3 months',
	},
	{
		_id: 1,
		name: 'Olivia Rhye',
		status: 'Active',
		course: 'Product Designer',
		emailAddress: 'olivia@untitledui.com',
		duration: '3 months',
	},
	{
		_id: 2,
		name: 'Sanyaolu Rhye',
		status: 'Active',
		course: 'Product Designer',
		emailAddress: 'olivia@untitledui.com',
		duration: '3 months',
	},
	{
		_id: 3,
		name: 'Fakile Rhye',
		status: 'Active',
		course: 'Product Designer',
		emailAddress: 'fakile@gmail.com',
		duration: '3 months',
	},
	{
		_id: 4,
		name: 'Fatokun Rhye',
		status: 'Active',
		course: 'UI/UX Designer',
		emailAddress: 'hello@untitledui.com',
		duration: '3 months',
	},
	{
		_id: 1,
		name: 'Olivia Rhye',
		status: 'Active',
		course: 'Product Designer',
		emailAddress: 'olivia@untitledui.com',
		duration: '3 months',
	},
	{
		_id: 2,
		name: 'Sanyaolu Rhye',
		status: 'Active',
		course: 'Product Designer',
		emailAddress: 'olivia@untitledui.com',
		duration: '3 months',
	},
	{
		_id: 3,
		name: 'Fakile Rhye',
		status: 'Active',
		course: 'Product Designer',
		emailAddress: 'fakile@gmail.com',
		duration: '3 months',
	},
	{
		_id: 4,
		name: 'Fatokun Rhye',
		status: 'Active',
		course: 'UI/UX Designer',
		emailAddress: 'hello@untitledui.com',
		duration: '3 months',
	},
	{
		_id: 1,
		name: 'Olivia Rhye',
		status: 'Active',
		course: 'Product Designer',
		emailAddress: 'olivia@untitledui.com',
		duration: '3 months',
	},
	{
		_id: 2,
		name: 'Sanyaolu Rhye',
		status: 'Active',
		course: 'Product Designer',
		emailAddress: 'olivia@untitledui.com',
		duration: '3 months',
	},
	{
		_id: 3,
		name: 'Fakile Rhye',
		status: 'Active',
		course: 'Product Designer',
		emailAddress: 'fakile@gmail.com',
		duration: '3 months',
	},
	{
		_id: 4,
		name: 'Fatokun Rhye',
		status: 'Active',
		course: 'UI/UX Designer',
		emailAddress: 'hello@untitledui.com',
		duration: '3 months',
	},
	{
		_id: 1,
		name: 'Olivia Rhye',
		status: 'Active',
		course: 'Product Designer',
		emailAddress: 'olivia@untitledui.com',
		duration: '3 months',
	},
	{
		_id: 2,
		name: 'Sanyaolu Rhye',
		status: 'Active',
		course: 'Product Designer',
		emailAddress: 'olivia@untitledui.com',
		duration: '3 months',
	},
	{
		_id: 3,
		name: 'Fakile Rhye',
		status: 'Active',
		course: 'Product Designer',
		emailAddress: 'fakile@gmail.com',
		duration: '3 months',
	},
	{
		_id: 4,
		name: 'Fatokun Rhye',
		status: 'Active',
		course: 'UI/UX Designer',
		emailAddress: 'hello@untitledui.com',
		duration: '3 months',
	},
	{
		_id: 1,
		name: 'Olivia Rhye',
		status: 'Active',
		course: 'Product Designer',
		emailAddress: 'olivia@untitledui.com',
		duration: '3 months',
	},
	{
		_id: 2,
		name: 'Sanyaolu Rhye',
		status: 'Active',
		course: 'Product Designer',
		emailAddress: 'olivia@untitledui.com',
		duration: '3 months',
	},
	{
		_id: 3,
		name: 'Fakile Rhye',
		status: 'Active',
		course: 'Product Designer',
		emailAddress: 'fakile@gmail.com',
		duration: '3 months',
	},
	{
		_id: 4,
		name: 'Fatokun Rhye',
		status: 'Active',
		course: 'UI/UX Designer',
		emailAddress: 'hello@untitledui.com',
		duration: '3 months',
	},
	{
		_id: 1,
		name: 'Olivia Rhye',
		status: 'Active',
		course: 'Product Designer',
		emailAddress: 'olivia@untitledui.com',
		duration: '3 months',
	},
	{
		_id: 2,
		name: 'Sanyaolu Rhye',
		status: 'Active',
		course: 'Product Designer',
		emailAddress: 'olivia@untitledui.com',
		duration: '3 months',
	},
	{
		_id: 3,
		name: 'Fakile Rhye',
		status: 'Active',
		course: 'Product Designer',
		emailAddress: 'fakile@gmail.com',
		duration: '3 months',
	},
	{
		_id: 4,
		name: 'Fatokun Rhye',
		status: 'Active',
		course: 'UI/UX Designer',
		emailAddress: 'hello@untitledui.com',
		duration: '3 months',
	},
	{
		_id: 1,
		name: 'Olivia Rhye',
		status: 'Active',
		course: 'Product Designer',
		emailAddress: 'olivia@untitledui.com',
		duration: '3 months',
	},
	{
		_id: 2,
		name: 'Sanyaolu Rhye',
		status: 'Active',
		course: 'Product Designer',
		emailAddress: 'olivia@untitledui.com',
		duration: '3 months',
	},
	{
		_id: 3,
		name: 'Fakile Rhye',
		status: 'Active',
		course: 'Product Designer',
		emailAddress: 'fakile@gmail.com',
		duration: '3 months',
	},
	{
		_id: 4,
		name: 'Fatokun Rhye',
		status: 'Active',
		course: 'UI/UX Designer',
		emailAddress: 'hello@untitledui.com',
		duration: '3 months',
	},
	{
		_id: 1,
		name: 'Olivia Rhye',
		status: 'Active',
		course: 'Product Designer',
		emailAddress: 'olivia@untitledui.com',
		duration: '3 months',
	},
	{
		_id: 2,
		name: 'Sanyaolu Rhye',
		status: 'Active',
		course: 'Product Designer',
		emailAddress: 'olivia@untitledui.com',
		duration: '3 months',
	},
	{
		_id: 3,
		name: 'Fakile Rhye',
		status: 'Active',
		course: 'Product Designer',
		emailAddress: 'fakile@gmail.com',
		duration: '3 months',
	},
	{
		_id: 4,
		name: 'Fatokun Rhye',
		status: 'Active',
		course: 'UI/UX Designer',
		emailAddress: 'hello@untitledui.com',
		duration: '3 months',
	},
	{
		_id: 1,
		name: 'Olivia Rhye',
		status: 'Active',
		course: 'Product Designer',
		emailAddress: 'olivia@untitledui.com',
		duration: '3 months',
	},
	{
		_id: 2,
		name: 'Sanyaolu Rhye',
		status: 'Active',
		course: 'Product Designer',
		emailAddress: 'olivia@untitledui.com',
		duration: '3 months',
	},
	{
		_id: 3,
		name: 'Fakile Rhye',
		status: 'Active',
		course: 'Product Designer',
		emailAddress: 'fakile@gmail.com',
		duration: '3 months',
	},
	{
		_id: 4,
		name: 'Fatokun Rhye',
		status: 'Active',
		course: 'UI/UX Designer',
		emailAddress: 'hello@untitledui.com',
		duration: '3 months',
	},
	{
		_id: 1,
		name: 'Olivia Rhye',
		status: 'Active',
		course: 'Product Designer',
		emailAddress: 'olivia@untitledui.com',
		duration: '3 months',
	},
	{
		_id: 2,
		name: 'Sanyaolu Rhye',
		status: 'Active',
		course: 'Product Designer',
		emailAddress: 'olivia@untitledui.com',
		duration: '3 months',
	},
	{
		_id: 3,
		name: 'Fakile Rhye',
		status: 'Active',
		course: 'Product Designer',
		emailAddress: 'fakile@gmail.com',
		duration: '3 months',
	},
	{
		_id: 4,
		name: 'Fatokun Rhye',
		status: 'Active',
		course: 'UI/UX Designer',
		emailAddress: 'hello@untitledui.com',
		duration: '3 months',
	},
	{
		_id: 1,
		name: 'Olivia Rhye',
		status: 'Active',
		course: 'Product Designer',
		emailAddress: 'olivia@untitledui.com',
		duration: '3 months',
	},
	{
		_id: 2,
		name: 'Sanyaolu Rhye',
		status: 'Active',
		course: 'Product Designer',
		emailAddress: 'olivia@untitledui.com',
		duration: '3 months',
	},
	{
		_id: 3,
		name: 'Fakile Rhye',
		status: 'Active',
		course: 'Product Designer',
		emailAddress: 'fakile@gmail.com',
		duration: '3 months',
	},
	{
		_id: 4,
		name: 'Fatokun Rhye',
		status: 'Active',
		course: 'UI/UX Designer',
		emailAddress: 'hello@untitledui.com',
		duration: '3 months',
	},
	{
		_id: 1,
		name: 'Olivia Rhye',
		status: 'Active',
		course: 'Product Designer',
		emailAddress: 'olivia@untitledui.com',
		duration: '3 months',
	},
	{
		_id: 2,
		name: 'Sanyaolu Rhye',
		status: 'Active',
		course: 'Product Designer',
		emailAddress: 'olivia@untitledui.com',
		duration: '3 months',
	},
	{
		_id: 3,
		name: 'Fakile Rhye',
		status: 'Active',
		course: 'Product Designer',
		emailAddress: 'fakile@gmail.com',
		duration: '3 months',
	},
	{
		_id: 4,
		name: 'Fatokun Rhye',
		status: 'Active',
		course: 'UI/UX Designer',
		emailAddress: 'hello@untitledui.com',
		duration: '3 months',
	},
	{
		_id: 1,
		name: 'Olivia Rhye',
		status: 'Active',
		course: 'Product Designer',
		emailAddress: 'olivia@untitledui.com',
		duration: '3 months',
	},
	{
		_id: 2,
		name: 'Sanyaolu Rhye',
		status: 'Active',
		course: 'Product Designer',
		emailAddress: 'olivia@untitledui.com',
		duration: '3 months',
	},
	{
		_id: 3,
		name: 'Fakile Rhye',
		status: 'Active',
		course: 'Product Designer',
		emailAddress: 'fakile@gmail.com',
		duration: '3 months',
	},
	{
		_id: 4,
		name: 'Fatokun Rhye',
		status: 'Active',
		course: 'UI/UX Designer',
		emailAddress: 'hello@untitledui.com',
		duration: '3 months',
	},
	{
		_id: 1,
		name: 'Olivia Rhye',
		status: 'Active',
		course: 'Product Designer',
		emailAddress: 'olivia@untitledui.com',
		duration: '3 months',
	},
	{
		_id: 2,
		name: 'Sanyaolu Rhye',
		status: 'Active',
		course: 'Product Designer',
		emailAddress: 'olivia@untitledui.com',
		duration: '3 months',
	},
	{
		_id: 3,
		name: 'Fakile Rhye',
		status: 'Active',
		course: 'Product Designer',
		emailAddress: 'fakile@gmail.com',
		duration: '3 months',
	},
	{
		_id: 4,
		name: 'Fatokun Rhye',
		status: 'Active',
		course: 'UI/UX Designer',
		emailAddress: 'hello@untitledui.com',
		duration: '3 months',
	},
];
